#docker-compose.yml

version: "3"

services:
  reverse-proxy:
    container_name: reverse-proxy
    image: nginx
    depends_on: -child-maintenance-calculator
    ports:
      - 80:80
    volumes:
      - ./ReverseProxy/nginx.conf:/etc/nginx/nginx.conf

  child-maintenance-calculator:
    container_name: child-maintenance-calculator
    image: bryndukes/child-maintenance-calculator:latest
    build:
      context: .
    ports:
      - 8080:80
    restart: on-failure
