version: "3"

services:
  proxy:
    container_name: nginx
    image: nginx:latest
    depends_on:
      - child-maintenance-calculator
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    networks:
      - mynetwork
  
  child-maintenance-calculator:
    container_name: child-maintenance-calculator
    image: bryndukes/child-maintenance-calculator:latest
    ports:
      - "5000:5000"
    networks:
      - mynetwork
    build:
      context: .
    restart: on-failure

  networks:
    mynetwork:
      driver: bridge