#docker-compose.yml

version: "3"

services:
  proxy:
    container_name: "nginxcore"
    image: nginx-core # Our custom NGINX Docker image
    build:
      context: ./ReverseProxy/
    ports:
      - "8083:80" # Expose the port 80 from the service to the host at 8081  
    networks:
      - mynetwork
  
  child-maintenance-calculator:
    container_name: child-maintenance-calculator
    image: bryndukes/child-maintenance-calculator:latest
    build:
      context: .
    restart: on-failure
    
    networks:
      - mynetwork
  
networks:
  mynetwork: # User-Defined Network with the name mynetwork  
    driver: bridge